### ISSUE TITLE
Missing code of conduct

### ISSUE THREAD

**Issue by angrox** [fkurz/vpnctl#2]
Please add a Code of Conduct to your project. 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project. 

see also: https://opensource.guide/code-of-conduct/

**Comment by fkurz** [comment]
Code of conduct has been added: https://github.com/fkurz/vpnctl/blob/main/CODE_OF_CONDUCT.md Thanks! :)
